name: nightly-snapshot
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create empty commit for snapshot
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          git commit --allow-empty -m "chore: nightly snapshot $(date -u +%F)"
      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
